### ISSUE TITLE
"QuickSortArray" instead of "QuickSort"

### ISSUE THREAD

**Issue by happygithuber** [jonadv/VBA-Benchmark#2]
**'REMARK:
'when using VBA-Benchmark = cBenchmark.bas
'you need to change "QuickSort" with "QuickSortArray"
'in line 720 + 721**

If (inLow < tmpHi) Then QuickSortArray vArray, inLow, tmpHi
If (tmpLow < inHi) Then QuickSortArray vArray, tmpLow, inHi

instead of
If (inLow < tmpHi) Then QuickSort vArray, inLow, tmpHi
If (tmpLow < inHi) Then QuickSort vArray, tmpLow, inHi

**Comment by jonadv** [comment]
It was referring a local function, outside of this class. Fixed it, thank you.
