### ISSUE TITLE
VBA error with conditional Directives

### ISSUE THREAD

**Issue by Shaun849** [jonadv/VBA-Benchmark#3]
Hi @jonadv , thanks for a very useful piece of work. 
Have a couple of questions (of which this is the first) assuming you are still developing this...

I get a compile error with the conditional directives (32bit lines below). Not a problem for me as I'm running on 64 bit system so I just rem them out, but wondering what the cause would be?
```VBA

#If VBA7 Then   '64 bit
    Private Declare PtrSafe Function QueryPerformanceCounter Lib "kernel32" (stamp As Currency) As Byte
    Private Declare PtrSafe Function QueryPerformanceFrequency Lib "kernel32" (freq As Currency) As Byte
#Else           '32 bit
    Private Declare Function QueryPerformanceCounter Lib "kernel32" (stamp As Currency) As Byte
    Private Declare Function QueryPerformanceFrequency Lib "kernel32" (freq As Currency) As Byte
#End If
```

**Comment by Shaun849** [comment]
Hi, I have since realised that this appears to be an Excel VBA Editor rendering error and in fact the code runs fine. In the Editor it is shown in red (indicating a fault) but seems to run  OK. Apologies!
![image](https://github.com/jonadv/VBA-Benchmark/assets/137066820/7cafe0de-88b7-4e05-92c9-0bfda0ebd270)

**Comment by Shaun849** [comment]
Hi @jonadv, thanks for responding! Are you contactable via PMs? - I've got a couple of questions about your highly useful vba class - if you are still developing...
Apologies if I'm doing this in the wrong way - I'm not familiar with github and it's ways - only just joined  after coming across your vba benchmark code via web search...

**Comment by jonadv** [comment]
@Shaun849 sure send me a message on Gitter

[@jonadv-60d8ee4c6da03739847fcfb7:gitter.im](https://matrix.to/#/@jonadv-60d8ee4c6da03739847fcfb7:gitter.im)

**Comment by jonadv** [comment]
I created a Gitter chat room for this repository:
https://matrix.to/#/!YTxrWpbmQEslnKgmOD:gitter.im?via=gitter.im

**Comment by Shaun849** [comment]
> [@jonadv-60d8ee4c6da03739847fcfb7:gitter.im](https://matrix.to/#/@jonadv-60d8ee4c6da03739847fcfb7:gitter.im)
Well, setup messaging, but  am refused entry to the Glitter chat room...
I just get a message saying "You are not invited to this room" :-(
